# Site settings
title: Daniel Ni
email: danielni@wustl.edu
author: Daniel Ni
description: "My personal site."
baseurl: ""
url: "http://danielni.github.io"
google_analytics: 

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
paginate_path: "blog/page:num"
